%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/jazzy/.*$
%global __requires_exclude_from ^/opt/ros/jazzy/.*$

Name:           ros-jazzy-crane-plus-examples
Version:        3.0.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS crane_plus_examples package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       opencv-devel
Requires:       ros-jazzy-crane-plus-control
Requires:       ros-jazzy-crane-plus-description
Requires:       ros-jazzy-crane-plus-moveit-config
Requires:       ros-jazzy-cv-bridge
Requires:       ros-jazzy-geometry-msgs
Requires:       ros-jazzy-image-geometry
Requires:       ros-jazzy-moveit-ros-planning-interface
Requires:       ros-jazzy-rclcpp
Requires:       ros-jazzy-tf2-geometry-msgs
Requires:       ros-jazzy-usb-cam
Requires:       ros-jazzy-ros-workspace
BuildRequires:  opencv-devel
BuildRequires:  ros-jazzy-ament-cmake
BuildRequires:  ros-jazzy-crane-plus-control
BuildRequires:  ros-jazzy-crane-plus-description
BuildRequires:  ros-jazzy-crane-plus-moveit-config
BuildRequires:  ros-jazzy-cv-bridge
BuildRequires:  ros-jazzy-geometry-msgs
BuildRequires:  ros-jazzy-image-geometry
BuildRequires:  ros-jazzy-moveit-ros-planning-interface
BuildRequires:  ros-jazzy-rclcpp
BuildRequires:  ros-jazzy-tf2-geometry-msgs
BuildRequires:  ros-jazzy-usb-cam
BuildRequires:  ros-jazzy-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-jazzy-ament-lint-auto
BuildRequires:  ros-jazzy-ament-lint-common
%endif

%description
CRANE+ V2 examples package

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/jazzy" \
    -DAMENT_PREFIX_PATH="/opt/ros/jazzy" \
    -DCMAKE_PREFIX_PATH="/opt/ros/jazzy" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/jazzy

%changelog
* Fri Jan 31 2025 RT Corporation <shop@rt-net.jp> - 3.0.0-1
- Autogenerated by Bloom

